#!/usr/bin/env sh

openssl req -new -nodes -newkey rsa:4096 -keyout Cert.key -out Cert.csr -subj "/C=TH/ST=BKK/O=Grainify/OU=Ember/CN=Cert for localhost"
openssl x509 -req -sha256 -days 5120 -in Cert.csr -CA RootCA.pem -CAkey RootCA.key -CAcreateserial -extfile domains.ext -out Cert.crt
